version: '3.8'
services:
    postgres:
        image: postgres:14.1-alpine
        restart: always
        environment: 
          - POSTGRES_USER=postgres
          - POSTGRES_PASSWORD=postgres
        logging:
          options:
            max-size: 10m
            max-file: "3"
        ports:
          - 5432:5432
        volumes:
          - db:/var/lib/postgresql/data
          - ./sql/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql

    quarkus-app:
      build:
        context: .
        dockerfile: src/main/docker/Dockerfile.jvm
      image: urshortener/quarkus-app:native
      restart: always
      ports:
        - 8080:8080
      environment:
        - quarkus.datasource.jdbc.url=jdbc:postgresql://postgres:5432/postgres
        - quarkus.datasource.username=postgres
        - quarkus.datasource.password=postgres
        - quarkus.datasource.db-kind=postgresql
      depends_on:
        postgres:
          condition: service_started
volumes:
  db:
    driver: local